[workspace]
members = ["soml-compiler"]

[package]
name = "soml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soml-compiler = { path = "soml-compiler" }

clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.29", features = ["full"] }
tower-lsp = "0.19"
